[workspace]
members = [
    "dsnitch",
    "dsnitch-common",
    "xtask",
]
exclude = [
    "dsnitch-ebpf",
]
default-members = ["dsnitch"]
resolver = "2"

[workspace.dependencies]
aya = "0.14.0"
aya-log = "0.3.0"
bollard = "0.21.1"
futures-util = "0.3"
tokio = { version = "1.43", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
libc = "0.2"
